//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FrontServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrontServiceClient.IDecryptageService")]
    public interface IDecryptageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptageService/GetText", ReplyAction="http://tempuri.org/IDecryptageService/GetTextResponse")]
        string GetText();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptageService/GetText", ReplyAction="http://tempuri.org/IDecryptageService/GetTextResponse")]
        System.Threading.Tasks.Task<string> GetTextAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecryptageServiceChannel : Client.FrontServiceClient.IDecryptageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptageServiceClient : System.ServiceModel.ClientBase<Client.FrontServiceClient.IDecryptageService>, Client.FrontServiceClient.IDecryptageService {
        
        public DecryptageServiceClient() {
        }
        
        public DecryptageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetText() {
            return base.Channel.GetText();
        }
        
        public System.Threading.Tasks.Task<string> GetTextAsync() {
            return base.Channel.GetTextAsync();
        }
    }
}
